services:
  mediamtx:
    container_name: mediamtx
    image: bluenviron/mediamtx:latest
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./mediamtx.yml:/mediamtx.yml:ro
      - ./server.crt:/server.crt:ro
      - ./server.key:/server.key:ro
    
