per_listener_settings true

persistence true
persistence_location /var/lib/mosquitto/

log_dest stdout
log_type error
log_type warning
log_type notice
log_type information
connection_messages true

listener 8883
allow_anonymous true
require_certificate false
use_identity_as_username false

cafile /opt/mosquitto-oqs/certs/ca.crt
certfile /opt/mosquitto-oqs/certs/broker.crt
keyfile /opt/mosquitto-oqs/certs/broker.key

tls_version tlsv1.3